name: Setup Workflow
description: Composite action that sets up bun and installs dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - uses: uses: pnpm/action-setup@v3.0.0
      with:
        version: 8.6.1

    - run: pnpm install
      shell: bash
